### ISSUE TITLE
是否考虑基于最新版进行修改

### ISSUE THREAD

**Issue by hzinchengdu** [zhylmzr/weasel#2]
你好开发者，小狼毫最新版加入了很多特性，比如打字的性能也比0.14版本有所提高，emoji也支持彩色的。是否考虑基于最新版进行更新修改。

**Comment by zhylmzr** [comment]
暂不考虑，我看原版目前有很多崩溃报告，使用修改版目前还没有遇到过崩溃。

**Comment by hzinchengdu** [comment]
好的，感谢回复。
